apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

namePrefix: prod-

resources:
  - ../../base

replicas:
  - name: app
    count: 3

images:
  - name: myapp
    newTag: prod-latest

patches:
  - path: deployment-patch.yaml
  - path: hpa.yaml
